# Generated by Django 5.1.6 on 2025-02-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('about', models.TextField(blank=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('skills', models.TextField(blank=True, help_text='مهارت\u200cها را با کاما جدا کنید')),
                ('languages', models.TextField(blank=True, help_text='زبان\u200cها را با کاما جدا کنید')),
                ('edu1_degree', models.CharField(blank=True, max_length=100)),
                ('edu1_college', models.CharField(blank=True, max_length=150)),
                ('edu1_year', models.CharField(blank=True, max_length=4)),
                ('edu2_degree', models.CharField(blank=True, max_length=100)),
                ('edu2_college', models.CharField(blank=True, max_length=150)),
                ('edu2_year', models.CharField(blank=True, max_length=4)),
                ('edu3_degree', models.CharField(blank=True, max_length=100)),
                ('edu3_college', models.CharField(blank=True, max_length=150)),
                ('edu3_year', models.CharField(blank=True, max_length=4)),
                ('proj1_title', models.CharField(blank=True, max_length=150)),
                ('proj1_duration', models.CharField(blank=True, max_length=50)),
                ('proj1_description', models.TextField(blank=True)),
                ('proj2_title', models.CharField(blank=True, max_length=150)),
                ('proj2_duration', models.CharField(blank=True, max_length=50)),
                ('proj2_description', models.TextField(blank=True)),
                ('exp1_company', models.CharField(blank=True, max_length=150)),
                ('exp1_post', models.CharField(blank=True, max_length=150)),
                ('exp1_duration', models.CharField(blank=True, max_length=50)),
                ('exp1_description', models.TextField(blank=True)),
                ('exp2_company', models.CharField(blank=True, max_length=150)),
                ('exp2_post', models.CharField(blank=True, max_length=150)),
                ('exp2_duration', models.CharField(blank=True, max_length=50)),
                ('exp2_description', models.TextField(blank=True)),
                ('achievement_first', models.CharField(blank=True, max_length=255)),
                ('achievement_second', models.CharField(blank=True, max_length=255)),
                ('achievement_third', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
